# IMPORTANT: remote_theme for github pages, theme for local.
# github pages only wants me to use remote_theme.
# there's probably a way to make remote_theme work locally but i'm too lazy
# i probably should've just forked the theme. Oh well.
# theme: type-on-strap
remote_theme: sylhare/Type-on-Strap

# SITE CONFIGURATION
baseurl: ""
url: "https://mattnamara67.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Must Maintain                                    # site's title
description: "Stories and ramblings by Matt Namara"      # used by search engines
avatar:                          # None yet
favicon:                        # None yet


# Header and footer text
header_text: <h1>Must Maintain</h1><p>Stories and ramblings by Matt Namara</p>                                            # Change Blog header text
header_feature_image: assets/pretty-cropped.jpg

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image:                   # A bit transparent for color posts.

# Features
katex: false                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*"]
